### PR TITLE
sign_up_window

### PR DESCRIPTION
**Pull request by p0u74**

### CODE REVIEW

**Comment by alirzaMhd** [comment]
signup is not a good name for this module
sign_up_window would be better

**Comment by alirzaMhd** [comment]
Variable names should be lowercase with words separated by underscores, also called snake_case. For example: my_variable, this_is_a_variable.

Function names should be lowercase, with words separated by underscores. For example: my_function, this_is_a_function.

Class names should be written in CamelCase, starting with an uppercase first letter for each word. For example: MyClass, ThisIsAClass.

Constants should be written using all uppercase letters, with words separated by underscores. For example: MY_CONSTANT, THIS_IS_A_CONSTANT.

Private instance variables or methods should begin with a single underscore, like _my_var or _my_method.

Protected instance variables or methods should begin with a double underscore, like __my_var or __my_method.

Single letter variable names should be avoided, except in the case of loop iterators (e.g. for i in range(10)).

Variable names should be descriptive of their purpose, avoiding ambiguous or overly generic names.

The file name should be in all lowercase, with words separated by underscores. For example, "my_module_name.py".

**Comment by alirzaMhd** [comment]
add a reviewer to this pr

**Comment by alirzaMhd** [comment]
app = QApplication(sys.argv)
window = window()
window.show()
sys.exit(app.exec()) 
shouldn't this codes be on main module?

**Comment by alirzaMhd** [comment]
add a module for ico
don't just leave it there

**Comment by p0u74** [comment]
> codes be on main module

I understood all the cases except "codes have to be on main module"

**Pull request closed without merging**
